### ISSUE TITLE
kube-opa-violation-exporter release no longer exists

### ISSUE THREAD

**Issue by NFarrington** [cmacrae/helm-charts#1]
Hello and Happy New Year! 👋 

charts.cmacr.ae used to have a kube-opa-violation-exporter chart release for v0.2.0 of the chart. The entry still exists in charts.cmacr.ae, but the release for the chart seems to have disappeared from this repository (the Helm repo links to https://github.com/cmacrae/helm-charts/releases/download/kube-opa-violation-exporter-0.2.0/kube-opa-violation-exporter-0.2.0.tgz, which doesn't seem to exist anymore).

Would it be possible to restore this release, please?

**Comment by cmacrae** [comment]
Hey Neil, a **very** belated Happy New Year to you too! 👋 

Apologies for the delay on this - the project has undergone quite a big refactor, including the Helm charts.  

The new shiny chart ✨  can be found here: https://artifacthub.io/packages/helm/cmacrae/kove-deprecations
